default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :tests do
    scan(scheme: "BrainDays")
  end

  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(
      scheme: "BrainDays",
      devices: ["iPhone 15"]
    )
  end
end
