name: main workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run tests 
        run: |
          bundle exec fastlane ios tests